- .storybook/preview.ts
- src/app/recipeList/page.tsx
- src/components/ClientWrapper/RecipeListClient.tsx
> 레시피 리스트 페이지

- src/components/Card/DetailTextCard.tsx
- src/interfaces/cardInterface.ts
- src/stories/DetailTextCard.stories.tsx
> 레시피 상세페이지 content 컴포넌트 제작

- src/app/page.tsx
- src/components/Button/Cta.tsx
- close #36 
랜딩페이지 코멘트 수정사항 반영
> 랜딩페이지 수정사항

- src/components/ClientWrapper/RecipeListClient.tsx
- src/components/Pagination/Pagination.tsx
- src/interfaces/paginationInterface.ts
> 페이지네이션 타입 추가

- src/components/Card/MonthlyChallengeCard.tsx
- src/interfaces/cardInterface.ts
- src/stories/MonthlyChallengeCard.stories.tsx
- close #54 
스토리북 작동되지 않는 문제 해결. Chip 컴포넌트두개 연결.
- css 수정은 다음 issue로 미룸.
- 현재 이달의 챌린지 스토리북 때문에 스토리북 작동이 안되는 문제 발생했기 때문.
> 이달의 챌린지 카드 수정, 테스트

- src/components/Card/MonthlyChallengeCard.tsx
- src/interfaces/cardInterface.ts
- src/stories/MonthlyChallengeCard.stories.tsx
- tailwind.config.ts
- close #54 
- 만든 컴포넌트 실행 사진 아래 첨부
다음 작업 예정
- 이달의 랭커 카드 컴포넌트 만들기
> 이달의 챌린지 수정

- src/components/Card/ChallengeCard.tsx
- src/interfaces/cardInterface.ts
- src/stories/ChallengeCard.stories.tsx
- close #69 
- 글꼴은 무시하고 봐주세요. (왜인지 아직도 모르겠네요.)
나중 작업 예정.
- 챌린지 카드는 유저의 것 (본인 챌린지라면 삭제 가능)
- 이달의 챌린지 카드는 일단 목데이터로.
- 둘다 어드민이 삭제 가능
> 일반 챌린지 카드

- src/components/Card/WorkCard.tsx
- src/components/Modal/ImageEnlargeModal.tsx
- src/interfaces/modalInterface.ts
이미지 확대 모달 제작
- close #73 
다음에 할 작업
- 작업물 페이지의 피드백 컴포넌트 제작
> 이미지 확대 모달 제작

- src/components/Card/FeedbackCard.tsx
- src/components/Card/WorkCard.tsx
- src/components/Dropdown/CancelDropdown.tsx
- src/interfaces/dropdownInterface.ts
- src/interfaces/feedbackInterface.ts
- src/stories/FeedbackCard.stories.tsx
- close #71 
- 내가 쓴 댓글만 드롭다운 보임
- 드롭다운 눌렀을 때
- edit버튼 누르고 수정할 때
다음에 할 작업
- 작업물 페이지에 컴포넌트 연결
> 작업물 페이지 피드백 리스트 컴포넌트 제작

- src/components/Card/ChallengeDetailContentCard.tsx
- src/interfaces/cardInterface.ts
- src/stories/ChallengeDetailContent.stories.tsx
- close #75 
- 피그마 상으로는 이미지 두 개를 나란히 보게 되어있으나 화살표로 넘어다닐 수 있도록 구현했습니다.
> 챌린지 상세페이지 content

- package-lock.json
- package.json
- src/store/store.ts
> ✨ Feat:#99-initial setting

- hooks/useClientSyncStore.ts
- src/app/layout.tsx
- src/components/ClientWrapper/ChallengeRequestClient.tsx
- src/components/ClientWrapper/ClientSync.tsx
- src/components/ClientWrapper/SignInClient.tsx
- src/components/Nav/Nav.tsx
- src/store/store.ts
- close #126 
- true, falsy 사용하기
- fetch -> axios로 고치기
- 속도 개선.
- 챌린지 리스트 sort API 연결
- filterbar css 날아간 문제 해결
- cancel, abort API 연결
- id와 매치해서 본인 챌린지에 토글 뜨게 만들기 (id를 못불러오는 듯 함)
- 챌린지status patch - status만 보내도 됨.
- token 넘겨주어야 함.
> 로컬 스토리지 문제 해결하기

- src/api/api.ts
- src/components/Dropdown/Dropdown.tsx
- src/components/FilterBar/FilterBar.tsx
- src/interfaces/dropdownInterface.ts
> 챌린지 페이지 sort바 에러 수정

- src/components/Card/DetailTextCard.tsx
- src/components/Card/RecipeCard.tsx
- src/components/ClientWrapper/RecipeDetailClient.tsx
- src/components/ClientWrapper/RecipeListClient.tsx
- src/interfaces/recipelistInterface.ts
> 레시피 페이지 에러 수정

- src/components/Card/ChallengeParticipateStatus.tsx
- src/components/Card/FeedbackCard.tsx
- src/components/Card/WorkCard.tsx
- src/components/Input/WorkInput.tsx
- src/components/Modal/ImageEnlargeModal.tsx
- src/components/Nav/Nav.tsx
- src/stories/FeedbackCard.stories.tsx
- src/stories/WorkCard.stories.tsx
> 레시피 페이지 정렬 및 검색 

- public/ChallengeApplicationData.json
- src/api/challengeService.ts
- src/app/auth/challenge/page.tsx
- src/components/Body/ChallengeApplicationBody.tsx
- src/components/ClientWrapper/ChallengeMgmtClient.tsx
- src/components/Nav/Nav.tsx
- close #141
- api 제작이 아직 덜 돼서 api 커넥팅은 진행하지 못했습니다
> 어드민 신청 관리 페이지 제작

- src/components/ClientWrapper/ClosableModalClient.tsx
- src/components/Dropdown/ChallengeApplicationDropdown.tsx
- src/components/Header/MyChallengeHeader.tsx
- src/stories/MyChallengePage.stories.tsx
> 나의 챌린지 페이지 헤더

- src/components/Card/ChallengeParticipateStatus.tsx
- src/components/ClientWrapper/RecipeListClient.tsx
- src/components/Pagination/Pagination.tsx
> 챌린지 상세페이지 참여자 현황 ui 수정

- src/components/Card/ChallengeDetailContentCard.tsx
- src/components/ClientWrapper/ChallengeDetailClient.tsx
- src/components/OptionBox/OptionBox.tsx
- src/interfaces/cardInterface.ts
- src/interfaces/optionboxInterface.ts
> optionbox date 수정

- src/api/challengeService.ts
- src/components/ClientWrapper/ChallengeListClient.tsx
- src/components/ClientWrapper/RecipeListClient.tsx
- src/components/FilterBar/RecipeFilterBar.tsx
- src/interfaces/cardInterface.ts
> 챌린지 및 레시피 페이지 페이지네이션 비동기

- src/components/Header/ChallengeApplicationDetailHeader.tsx
- src/components/Pagination/Pagination.tsx
- src/interfaces/challengeInterface.ts
- src/interfaces/paginationInterface.ts
- src/stories/ChallengeApplicationDetailHeader.stories.tsx
- src/stories/Pagination.stories.tsx
> 어드민 신청관리 - 승인대기 header

- src/components/Body/ChallengeApplicationDetailBody.tsx
- src/interfaces/challengeInterface.ts
- src/stories/ChallengeApplicationDetailBody.stories.tsx
> 어드민 신청관리 - 승인대기 body

- src/api/feedbackService.ts
- src/app/challengeList/page.tsx
- src/components/Card/FeedbackCard.tsx
- src/components/Card/WorkCard.tsx
- src/interfaces/userInterface.ts
> 댓글 삭제 및 admin 유저 댓글 및 작업물 삭제 권한 

- src/app/page.tsx
- src/app/recipeList/page.tsx
- src/components/ClientWrapper/SignInClient.tsx
- src/components/ClientWrapper/SignUpClient.tsx
- src/stories/FeedbackCard.stories.tsx
- src/stories/WorkCard.stories.tsx
> 레시피 페이지 SSR & 로그인 상태일 때 렌딩, 로그인 ,회원가입 페이지에서 레시피 페이지로 이동

- hooks/useClientSyncStore.tsx
- src/components/ClientWrapper/SignInClient.tsx
- src/components/Modal/ProfileModal.tsx
- src/components/Nav/Nav.tsx
- src/store/store.ts
> 프로필 사진 누르면 프로필 모달 나오는 로직 제작

- src/components/Card/WorkCard.tsx
- src/components/ClientWrapper/SignUpClient.tsx
- src/components/Input/SignInput.tsx
- src/components/Nav/Nav.tsx
> 회원가입 페이지 반응형

- src/components/Card/FeedbackCard.tsx
- src/components/Card/WorkCard.tsx
- src/components/Input/WorkInput.tsx
- src/components/Modal/ImageEnlargeModal.tsx
> 작업물 페이지 반응형 디자인

- src/components/Card/DetailTextCard.tsx
- src/components/ClientWrapper/RecipeDetailClient.tsx
- src/interfaces/cardInterface.ts
- close #186 
- tablet
- mobile
> 레시피 상세 페이지 반응형 디자인

- src/components/ClientWrapper/SignInClient.tsx
- close #192 
[테블릿]
[모바일]
[미디어 쿼리]
- 챌린지 신청 페이지
- 랜딩 페이지
[챌린지 페이지]
- 챌린지 정렬 API CSR -> SSR 로직 변경
[알림]
- 웹 소켓 - socketio react 알림보내주기
- 공부하기
> 로그인 미디어 쿼리

- src/api/api.ts
- src/components/Card/ChallengeCard.tsx
- src/components/Card/MonthlyChallengeCard.tsx
- src/components/Card/MonthlyRankerCard.tsx
- src/components/ClientWrapper/ChallengeListClient.tsx
- src/components/ClientWrapper/RecipeListClient.tsx
- src/components/FilterBar/FilterBar.tsx
- src/components/Nav/Nav.tsx
- close #167 
[태블릿]
[모바일]
[미디어 쿼리]
- 로그인 페이지
- 챌린지 신청 페이지
- 랜딩 페이지
[챌린지 페이지]
- 챌린지 정렬 API CSR -> SSR 로직 변경
[알림]
- 웹 소켓 - socketio react 알림보내주기
- 공부하기
> 챌린지 리스트 미디어 쿼리

- src/components/ClientWrapper/ChallengeRequestClient.tsx
- close #195 
[테블릿]
PC와 동일
[모바일]
[유지보수]
- 지속적으로 테스트해서 문제 해결하기
- css
- 기능
- 성능
[챌린지 페이지]
- 챌린지 정렬 API CSR -> SSR 로직 변경
[알림]
- 웹 소켓 - socketio react 알림보내주기
- 공부하기
[라우터]
- 라우터 접근 제한 설정 (권한에 따라)
> 챌린지신청 미디어쿼리

- src/components/Card/ChallengeDetailContentCard.tsx
- src/components/Card/ChallengeMostLikedCard.tsx
- src/components/Card/ChallengeParticipateStatus.tsx
- src/components/ClientWrapper/ChallengeDetailClient.tsx
- src/components/Nav/Nav.tsx
- src/components/OptionBox/OptionBox.tsx
- src/interfaces/cardInterface.ts
- src/interfaces/challengelistInterface.ts
> 챌린지 상세페이지 미디어쿼리

- src/app/page.tsx
- src/components/Button/Cta.tsx
- src/components/ClientWrapper/ClosableModalClient.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Modal/ClosableModal.tsx
- close #194 
[태블릿]
[모바일]
[미디어 쿼리]
- 챌린지 신청 페이지
[챌린지 페이지]
- 챌린지 정렬 API CSR -> SSR 로직 변경
[알림]
- 웹 소켓 - socketio react 알림보내주기
- 공부하기
> 랜딩페이지 미디어 쿼리

- src/components/Body/ChallengeApplicationDetailBody.tsx
- src/components/Card/ChallengeDetailContentCard.tsx
- src/components/ClientWrapper/AdminChallengeDetailClient.tsx
- src/components/Header/ChallengeApplicationDetailHeader.tsx
- src/components/Modal/ConfirmModal.tsx
> 어드민 신청관리 상세페이지 미디어 쿼리

- src/api/challengeService.ts
- src/app/me/challenge/[id]/page.tsx
- src/app/me/page.tsx
- src/components/Body/ChallengeApplicationBody.tsx
- src/components/Body/ChallengeApplicationDetailBody.tsx
- src/components/Card/ChallengeCard.tsx
- src/components/ClientWrapper/ChallengeMgmtClient.tsx
- src/components/ClientWrapper/MyChallengeClient.tsx
- src/components/Dropdown/ChallengeApplicationDropdown.tsx
- src/components/Header/ChallengeApplicationDetailHeader.tsx
- src/components/Header/MyChallengeHeader.tsx
- src/interfaces/bodyInterface.ts
- src/interfaces/challengeInterface.ts
> 나의 챌린지 페이지 제작

- src/components/Card/ChallengeDetailContentCard.tsx
- src/components/Card/ChallengeRefPageCard.tsx
- src/components/Card/WorkCard.tsx
- src/components/ClientWrapper/ChallengeDetailClient.tsx
- src/components/ClientWrapper/ChallengeTryClient.tsx
- src/components/OptionBox/OptionBox.tsx
- src/interfaces/cardInterface.ts
- src/interfaces/optionboxInterface.ts
- src/interfaces/workInterface.ts
- close #214 
- embed 및 see content 버튼 둘 다 수정
> 작업물 도전하기 페이지 PUT & URL 연결 & 유튜브 임베드

- package-lock.json
- package.json
- src/components/Card/WorkCard.tsx
- src/styles/globals.css
- close #213 
- 작업물 content 받아서 보여줄 때 react에서 html 문자열을 직접 dom에 삽입해서 보여줬습니다.
- 보안상 위험이 있기 때문에 DOMPurify 패키지 사용해서 정화해주는 작업 진행했습니다.
> 텍스트 편집기로 작업물 생성 후 작업물 페이지에서 내용 받아올 수 있게 설정

- src/components/Card/ChallengeCard.tsx
- src/components/ClientWrapper/MyChallengeClient.tsx
- src/components/Header/MyChallengeHeader.tsx
> 나의 챌린지 페이지 반응형 제작

- src/components/Card/ChallengeCard.tsx
- src/components/ClientWrapper/ChallengeListClient.tsx
- src/components/ClientWrapper/MyChallengeClient.tsx
- src/interfaces/cardInterface.ts
- close #234
https://github.com/2-Docthru-team1/2-Docthru-team1-FE/issues/234
> 챌린지카드에 Keep going, View my work button 추가

- README.md
> Dev to Main readme 수정

- src/components/Nav/Nav.tsx
> Dev to Main 백엔드 주소 변경
